#! /bin/bash

set -e

# If no default port is set for this project, set it to 8000
if [ ! -n "$PORT" ]; then
  echo "Warning: No port specified. Using 8000."
  PORT=8000
fi

export DATABASE=$(ping -c 1 $DB_HOST > /dev/null 2>&1 && echo true || echo false)
run_command=$@

# Update any python requirements
update-requirements

# Wait for database to come up
if $DATABASE; then
    DATABASE=$(check-db-connection)
fi

# Run manage.py commands
if [ -n "$run_command" ]; then
    # If we have arguments, pass them to manage.py
    python manage.py $run_command
else
    # By default, prepare database and run server
    if $DATABASE; then
        python manage.py migrate --noinput
    fi
    python manage.py runserver 0.0.0.0:${PORT}
fi

